# docker-compose.yml

version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    networks:
      app_network:
        ipv4_address: 172.33.0.2
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      app_network:
        ipv4_address: 172.33.0.3




volumes:
  qdrant_storage:


networks:
  app_network:
    driver: bridge
    name: app_network
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16
